#+title:  TS-setting
#+author: TC
#+date:   2020-11-01

* Cara mengetahui service running
Untuk bisa mengetahui service yang sedang berjalan ada bebarapa perintah
bisa dilakukan 
** Mengetahui running untuk TS-Receiver
Pada dasarnya setiap socket server yang berjalan untuk menerima data dari
perangkat merupakan sebuah script yang menjalankan sebuah aplikasi biner 
yang terdapat dalam folder Trumon. Nama file biner tersebut adalah TcpServerTS1.
Untuk bisa mengetahui running TS-Receiver anda bisa menggunakan perintah ps[fn:1].
#+BEGIN_SRC bash
ps -axu | grep TcpServerTS1
#+END_SRC
Untuk mengecek service yang berjalan pada bash anda bisa menggunakan perintah 
berikut. Biasanya service diletakan pada file script bash maka untuk bisa melihat 
status file bash sedang berjalan atau tidak bisa menggunakan perintah tersebut.
#+BEGIN_SRC bash
ps -aux | grep start_Recv4421.sh
ps -aux | grep start_Parser.sh
ps -aux | grep PM.sh
#+END_SRC
* Install dependency
#+BEGIN_SRC bash
sudo apt-get install qt5-qmake-bin qt5-default libqt5sql5
#+END_SRC
* Menjalankan Aplikasi TS
Beberapa file sebaiknya disimpan dalam direktori /home/${USER} dimana ${USER} merupakan 
home direktori default ketika dan memasuki server melalui ssh.  Ada Folder yang bernama Trumon
dan pastikan beberapa file ada disana.
#+BEGIN_SRC BASH
tree
#+END_SRC
** Konfigurasi Socket Server
Untuk melakukan konfigurasi socket server anda bisa mengedit bagian file berikut.
** Konfiguasi ImageReconstrution
Image reconstruction digunakan untuk merubah file RAW yang merupakan Escape command menjadi 
file gambar (dalam format PNG)
** Konfigurasi OCR
OCR  digunakan untuk merubah file dari image kedalam bentuk text. Dalam pengembangannya 
Aplikasi TS pernah menggunakan aplikasi pihak ketiga. Beberapa kode terkadang diset oleh 
developer pihak ketiga atau menggunakan sebuah script yang dibuat prasimax untuk mengirimkan
data melalui perantara WEB-API. 
** Konfigurasi Parser 
Parser digunakan untuk memisahkan data teks kedalam beberapa komponent untuk bisa dimunculkan 
kedalam data transaksi.
* Stop Program
Beberapa methode bisa anda lakukan dengan untuk melakukan stop program. Anda bisa menggunakan
perintah top pada bash linux seperti contoh berikut untuk melihat aplikasi apa saja yang 
sedang berjalan di server
#+BEGIN_SRC
top
#+END_SRC
top diatas bisa digunakan untuk mendapatkan nilai PID dari tiap aplikasi yang sedang berajalan.
Dan anda bisa menjalankan kill untuk menghentikan aplikasi 
#+BEGIN_SRC
kill -9 <pid>
#+END_SRC
masukkan nilai <pid> dengan nilai pid yang tercantum dalam top atau ps -aux| grep <nama service>
Jika anda menggunakan ingin menghentikan perintah bash yang telah diekseksi terlalu banyak gunakan 
perintah berikut.

#+BEGIN_SRC
sudo killall sh
#+END_SRC
Jika anda menemukan proses berikut
#+BEGIN_SRC bash
ps -axu | grep PM.sh
almar 9723  0.0  0.0  11272  940 pts/3  S+   21:32   0:00 grep --color=auto PM.sh
#+END_SRC
maka anda telah mengekill semua proses sh. Dan satu satunya proses yang terdeteksi adalah proses
grep yang sedang mencari PM.sh yaitu ps -axu|grep PM.sh itu sendiri.
* Crontab
Jika anda ingin menjalankan program dalam crontab[fn:2] anda bisa menggunakan script crontab berikut. 
Jika kode dibawah tidak bisa berjalan di server anda, anda bisa merubah file ${HOME}
dengan login user yang anda miliki, pastinya ini dilakukan untuk bisa menjalankan schedule
pada aplikasi TS.
#+BEGIN_SRC
# engine pdc prasimax
 * * * * * /bin/sh /home/${HOME}/Trumon/PrintEmulator/PM.sh
 * * * * * /bin/sh /home/${HOME}/Trumon/Parser/start_Parser.sh
 * * * * * /bin/sh /home/${HOME}/Trumon/start_Recv3321.sh
 * * * * * /bin/sh /home/${HOME}/Trumon/start_Recv4421.sh
#+END_SRC

[fn:1] ps atau process status merupakan program untuk mengetahui program yang sedang berjalan
link referensi https://en.wikipedia.org/wiki/Ps_(Unix)

[fn:2] Crontab untuk schedulin  https://en.wikipedia.org/wiki/Cron
